name: Build Only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from asdf-python1 repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Make build.sh executable
      run: chmod +x ./build.sh
    - name: Make build.sh executable
      run: ./build.sh

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Make test.sh executable
      run: chmod +x ./test.sh
    - name: Make test.sh executable
      run: ./test.sh
