name: Build, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from main repo
      uses: actions/checkout@v2
    - name: Checkout scripts from 53490083 repo
      uses: actions/checkout@v2
      with:
        repository: macuta172/53490083
        path: scripts # Check out scripts into a subdirectory named scripts
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: List contents of scripts directory
      run: ls -la scripts
    - name: Build
      run: bash scripts/build.sh # Refer to build.sh in the scripts subdirectory

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from main repo
      uses: actions/checkout@v2
    - name: Checkout scripts from 53490083 repo
      uses: actions/checkout@v2
      with:
        repository: macuta172/53490083
        path: scripts
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Test
      run: bash scripts/test.sh

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from main repo
      uses: actions/checkout@v2
    - name: Checkout scripts from 53490083 repo
      uses: actions/checkout@v2
      with:
        repository: macuta172/53490083
        path: scripts
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Deploy
      run: bash scripts/deploy.sh

