name: Build Only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from asdf-python1 repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Make build.sh executable
        run: chmod +x ./build.sh
      - name: Run build.sh
        run: ./build.sh


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Make deploy.sh executable
        run: chmod +x ./deploy.sh
      - name: Run deploy.sh
        run: ./deploy.sh
