name: Build, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from main repo
      uses: actions/checkout@v2
    - name: Checkout build.sh from 53490083 repo
      uses: actions/checkout@v2
      with:
        repository: macuta172/53490083
        path: external-scripts
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: List contents of the directory where build.sh is located
      run: ls -la external-scripts
    - name: Make build.sh executable
      run: chmod +x external-scripts/build.sh
    - name: Build
      run: bash external-scripts/build.sh # Note the correct path here


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from main repo
      uses: actions/checkout@v2
    - name: Checkout scripts from 53490083 repo
      uses: actions/checkout@v2
      with:
        repository: macuta172/53490083
        path: scripts
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Test
      run: bash scripts/test.sh

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from main repo
      uses: actions/checkout@v2
    - name: Checkout scripts from 53490083 repo
      uses: actions/checkout@v2
      with:
        repository: macuta172/53490083
        path: scripts
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Deploy
      run: bash scripts/deploy.sh
